
CREATE SEQUENCE   "DEMO_CUST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 315 CACHE 20 NOORDER  NOCYCLE ;


CREATE TABLE  "PRODUCTS_LIST" 
   (	"ID" NUMBER, 
	"PRODUCTNAME" VARCHAR2(100), 
	"TOTALPRICE" FLOAT(126), 
	"QUANTITY" NUMBER, 
	 CONSTRAINT "PRODUCTS_LIST_PK" PRIMARY KEY ("ID") ENABLE
   ) ;

CREATE OR REPLACE TRIGGER  "BI_PRODUCTS_LIST" 
  before insert on "PRODUCTS_LIST"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "DEMO_CUST_SEQ".nextval into :NEW."ID" from dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_PRODUCTS_LIST" ENABLE;



